OrderManager
jschuiteboer/MolvenoRestaurant pull request #10
Opened 2018-03-15 14:26 UTC by Thorbecken

2018-03-16 07:12 UTC, jschuiteboer requested changes

2018-03-16 07:12 UTC, jschuiteboer commented on src/main/java/com/yacht/molvenorestaurant/business/OrderManager.java
> +    public ArrayList<Order> orders;
private

2018-03-16 07:12 UTC, jschuiteboer commented on src/main/java/com/yacht/molvenorestaurant/business/OrderManager.java
> +    public void markOrderComplete(Order order){
dit is een helper method voor `order.setComplete(true); updateOrder(order);`

2018-03-19 15:08 UTC, Agroeningen approved these changes

2018-03-21 15:16 UTC, merged